"""天凤 JSON 中对应的中文"""

"""役种"""
YAKU_NAMES = {
    "赤ドラ": "红宝牌",
    "立直": "立直",
    "ドラ": "宝牌",
    "断幺九": "断幺九",
    "平和": "平和",
    "門前清自摸和": "门前清自摸和",
    "裏ドラ": "里宝牌",
    "一発": "一发",
    "役牌:場風牌": "役牌 场风牌",
    "役牌:自風牌": "役牌 自风牌",
    "役牌 發": "役牌 发",
    "役牌 白": "役牌 白",
    "役牌 中": "役牌 中",
    "混一色": "混一色",
    "一盃口": "一杯口",
    "三色同順": "三色同顺",
    "対々和": "对对和",
    "七対子": "七对子",
    "一気通貫": "一气通贯",
    "混全帯幺九": "混全带幺九",
    "清一色": "清一色",
    "三暗刻": "三暗刻",
    "河底撈魚": "河底捞鱼",
    "純全帯幺九": "纯全带幺九",
    "海底摸月": "海底摸月",
    "嶺上開花": "岭上开花",
    "ダブル立直": "两立直",
    "小三元": "小三元",
    "槍槓": "抢杠",
    "混老頭": "混老头",
    "三色同刻": "三色同刻",
    "二盃口": "二杯口",
    "四暗刻": "四暗刻",
    "大三元": "大三元",
    "国士無双": "国士无双",
    "小四喜": "小四喜",
    "字一色": "字一色",
    "四暗刻単騎": "四暗刻单骑",
    "三槓子": "三杠子",
    "清老頭": "清老头",
    "天和": "天和",
    "地和": "地和",
    "緑一色": "绿一色",
    "国士無双１３面": "国士无双十三面",
    "大四喜": "大四喜",
    "四槓子": "四杠子",
    "九蓮宝燈": "九莲宝灯",
    "純正九蓮宝燈": "纯正九莲宝灯",
    "Red Five": "红宝牌",
    "Riichi": "立直",
    "Dora": "宝牌",
    "All Simples": "断幺九",
    "Pinfu": "平和",
    "Fully Concealed Hand": "门前清自摸和",
    "Ura Dora": "里宝牌",
    "Ippatsu": "一发",
    "Prevalent Wind": "役牌 场风牌",
    "Seat Wind": "役牌 自风牌",
    "Green Dragon": "役牌 发",
    "White Dragon": "役牌 白",
    "Red Dragon": "役牌 中",
    "Half Flush": "混一色",
    "Pure Double Sequence": "一杯口",
    "Mixed Triple Sequence": "三色同顺",
    "All Triplets": "对对和",
    "Seven Pairs": "七对子",
    "Pure Straight": "一气通贯",
    "Half Outside Hand": "混全带幺九",
    "Full Flush": "清一色",
    "Three Concealed Triplets": "三暗刻",
    "Under the River": "河底捞鱼",
    "Fully Outside Hand": "纯全带幺九",
    "Under the Sea": "海底摸月",
    "After a Kan": "岭上开花",
    "Double Riichi": "两立直",
    "Little Three Dragons": "小三元",
    "Robbing a Kan": "抢杠",
    "All Terminals and Honors": "混老头",
    "Triple Triplets": "三色同刻",
    "Twice Pure Double Sequence": "二杯口",
    "Four Concealed Triplets": "四暗刻",
    "Big Three Dragons": "大三元",
    "Thirteen Orphans": "国士无双",
    "Four Little Winds": "小四喜",
    "All Honors": "字一色",
    # "四暗刻単騎": "四暗刻单骑",
    "Three Quads": "三杠子",
    "All Terminals": "清老头",
    "Blessing of Heaven": "天和",
    "Blessing of Earth": "地和",
    "All Green": "绿一色",
    # "国士無双１３面": "国士无双十三面",
    "Four Big Winds": "大四喜",
    "Four Quads": "四杠子",
    "Nine Gates": "九莲宝灯",
    "True Nine Gates": "纯正九莲宝灯",
}
